#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER synapse WITH PASSWORD '$SYNAPSE_POSTGRES_PASSWORD';
  CREATE DATABASE synapse;
  GRANT ALL PRIVILEGES ON DATABASE synapse TO synapse;

  CREATE USER mas WITH PASSWORD '$MATRIX_AUTHENTICATION_SERVICE_POSTGRES_PASSWORD';
  CREATE DATABASE mas;
  GRANT ALL PRIVILEGES ON DATABASE mas TO mas;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname synapse <<-EOSQL
  GRANT ALL ON SCHEMA public TO synapse;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname mas <<-EOSQL
  GRANT ALL ON SCHEMA public TO mas;
EOSQL
